site_name: yavda1.github.io
site_url: https://yavda1.github.io/

theme:
  name: slate
markdown_extensions:
    - admonition

nav:
    - Home: index.md
    - Guides:
        - guides/boot2vwii.md
        - guides/pksmtwilight.md
        - guides/gm9formatsd.md
       
